### PR TITLE
GetSubjectSpaces iterates paginated responses

### LINKED ISSUE #59: `GET /networking/v1/external/policies` missing policies from paginated spaces
## Issue

```
As a user has access to more spaces than the pagination limit (50)
When I request a list of network policies
Then I should see policies from all of the spaces I have access to
```

At the moment the API only looks at the first page of spaces, so any network policies that relate to subsequent spaces won't be listed in the results.

## Context

Our tenants reported a "weird issue" whereby they'd run

```
cf add-network-policy ...
```

and then immediately run:

```
cf network-policies
```

But couldn't find the network policy they'd just added.

This only happened for some users - if you created a new user with access only to that space you could see the network-policies just fine.

Some investigation pointed us at [src/policy-server/cc_client/client.go](https://github.com/cloudfoundry/cf-networking-release/blob/6414240cfc01d74c001a9de5dec347169f89959b/src/policy-server/cc_client/client.go#L284-L302) which looks like it doesn't attempt to walk through the pagination.

## Steps to Reproduce

Prepare a user with access to more than 50 spaces:

```
cf create-org test-policy-bug
cf target -o test-policy-bug

cf create-user j.smith@example.com S3cr3tS3cr3t

for i in $(seq 1 60); do
    cf create-space space-$i
    cf set-space-role j.smith@example.com test-policy-bug space-$i SpaceDeveloper
    
done

```
Also one user with access to only space-60
```
cf create-user j.smith2@example.com S3cr3tS3cr3t
cf set-space-role j.smith2@example.com test-policy-bug space-60 SpaceDeveloper

``` 

Login with the user with > 50 spaces, deploy a pair of apps, and setup the policy
```
cf login -u j.smith@example.com -p S3cr3tS3cr3t
cf target -o test-policy-bug -s space-60

mkdir -p /tmp/test-app
touch /tmp/test-app/Staticfile /tmp/test-app/index.html
cf push app1 -p /tmp/test-app
cf push app2 -p /tmp/test-app

cf add-network-policy app1 --destination-app app2
```

The user cannot see the policy! But the policy is working fine

```
$ cf network-policies
Listing network policies in org test-policy-bug / space space-60 as j.smith@example.com...

source   destination   protocol   ports
$
```

But other user with only one space is be able, the same for an admin user

```
$ cf login -u j.smith2@example.com -p S3cr3tS3cr3t
....
$ cf target -o test-policy-bug -s space-60
....
$ cf network-policies
Listing network policies in org test-policy-bug / space space-60 as j.smith@example.com...

source   destination   protocol   ports
$
```

## Expected result

It should list all of the network policies from the spaces that the user has access to.

## Current result

It only includes network policies that relate to spaces on the first page of results.

## Possible Fix

See #60

### PR DESCRIPTION
**Pull request by richardTowers**
Fixes #59.

The CC api would paginate the responses for multiple resources
including the spaces that a user belongs to. The default
pagination size is 50 elements.

If a user belongs to more than 50 spaces, the verification of
policies that the user has access to might fail, as not all the
spaces are retrieved properly.

This commit fixes the specific method cc_client.GetSubjectSpaces,
but a better approach would be create a PaginatedJSONClient
that would wrap json_client.JsonClient to iterate any
paginated response, but that might require more changes across
the code.

### CODE REVIEW

**Comment by ameowlia** [comment]
Hi @richardTowers, Thanks for this PR! We'll prioritize it soon.

Amelia, CF Container Networking Team Member

File: src/policy-server/cc_client/client_test.go [hunk 1]
```diff
@@ -422,8 +424,22 @@ var _ = Describe("Client", func() {
...
+				parsedRoute, err := url.Parse(route)
+				Expect(err).NotTo(HaveOccurred())
+				pageParameter := parsedRoute.Query().Get("page")
+				if pageParameter == "" {
+					pageParameter = "1"
+				}
+				page, err := strconv.Atoi(pageParameter)
+				Expect(err).NotTo(HaveOccurred())
+				response := responses[page - 1]
+				_ = json.Unmarshal([]byte(response), respData)
```
Comment (XanderStrike) [inline src/policy-server/cc_client/client_test.go]: I know it's just a fixture, but can we check the error here (e.g. in case someone tries to update the fixture and messes it up)?

File: src/policy-server/cc_client/client.go [hunk 2]
```diff
@@ -286,14 +292,19 @@ func (c *Client) GetSubjectSpaces(token, subjectId string) (map[string]struct{},
 
 	route := fmt.Sprintf("/v2/users/%s/spaces", subjectId)
```
Comment (XanderStrike) [inline src/policy-server/cc_client/client.go]: Can we default `results-per-page` to 100 (the maximum)? That will cut the number of requests in half.
